### ISSUE TITLE
empty value in http query

### ISSUE THREAD

**Issue by boborjan2** [dobrosi/jozsefutca#15]
igyu, most latom, h ilyen hivasok is mennek:
 /api/icom?gvol=&rvol=&cvol=&hvol=&mvol=&type=codefon&code=
Ezt most megcsinaltam, h igonoralja (empty value), de jobb lenne, ha nem is kuldenel ilyet majd

**Comment by dobrosi** [comment]
Raktam validaciot a kliensre.
