### ISSUE TITLE
Nem hallatszik a beep a mode-okba való belépéskor

### ISSUE THREAD

**Issue by j4v4d3m0** [dobrosi/jozsefutca#2]
Korábban működött, hallottam. Valamiért egy ideje vagy nagyon halk, de inkább teljesen néma.

**Comment by dobrosi** [comment]
Nem volt felvéve a beep hangereje. Pontosabban 0-ra volt áálítva az Webe GUI admin felületen.

**Comment by dobrosi** [comment]
Nem volt felvéve a beep hangereje. Pontosabban 0-ra volt áálítva az Webe GUI admin felületen.
