### ISSUE TITLE
Hiba a HTTP headerekkel: Header fields are too long for server to interpret

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#24]
``
curl -H "User-Agent: 12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345" -H "Meg-Egy-Header: Ami mar sok" http://kaputelefon.local/api/mac
``

Ha a User-Agent-re beallitottam rovidebbet (alapbol vmi ilyen:
Mozilla/5.0 (Linux; Android 11; LM-Q710(FGN)) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/92.0.4515.159 Mobile Safari/537.36), akkor
nem kaptam a hibat, ami ez:

Header fields are too long for server to interpret

Ez a problema sajnos jelentkezik nalam 3 felekeppen:
- A sajat kaputelefon alkalmazasban (amit kuldtem). Szerencsere itt
megoldom, mert tudok hatassal lenni a HTTP headerekre, mint pl a
User-Agent-re is. Tehat vegulis itt nem gaz, itt megoldva.
- A playben levo Bonjour kliens alkalmazasban ugyanugy, mint nalam.
Itt mondjuk ven egy olyan, hogy lehet valasztani, hogy egy kulso
bongeszoben nyissa meg a feloldott domain IP-jevel, akkor nincs hiba.
- Captive paggel, az egyik (raadsul ujabb Android) verzional, mert
gondolom pont ugy halmozodik fel a http header hossz. Erre semmilyen
workaround nincs.

**Comment by boborjan2** [comment]
solved in 0.1.6. Header and uri length are both maxed at 2048
