### ISSUE TITLE
A favicon kezelése

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#34]
Mindig megy egy kérés a favicon-ra, mai most ráadásul redirect-et okoz az index page-re.
Nem kell favicon, vagy embeded legyen.

**Comment by boborjan2** [comment]
A favicon-t az te kered le (ugy ertem a mi hatml cuccunk?) Mer az akkor mehetne ezzel a gulp cuccossal: (ezt hasznalom a cd valtonal)
var gulp = require('gulp');
var inlinesource = require('gulp-inline-source');
var gzip = require('gulp-gzip');
var inlineimg = require('gulp-inline-image-html');

gulp.task('inlinesource', function () {
	    return gulp.src('html/*.html')
			.pipe(inlineimg('html'))
	        .pipe(inlinesource())
			.pipe(gzip({ gzipOptions: { level: 9 } }))
	        .pipe(gulp.dest('build'));
});

**Comment by dobrosi** [comment]
kész
