### ISSUE TITLE
Az auth config Mentés gombra újraindul a kaputelefon STA módban.

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#36]
Az auth config Mentés gombra újraindul a kaputelefon STA módban.
Szerintem ez a workflow nem jó. Ráadásul ez a legfelső beállítás, ami után elúszik a backend a frontend alól.

Legalabb figyelmeztetés kellene, vagy Mentés és újraindítás gomb.

Vagy a kliensben felugró ablak, amiben dönthet a user:
Mentés és újraindítás / Mentés

Inkább a kliens oldal indítson újra. Ha a kaputelefon újraindul, akkor ne egy kapcsolat megszakad legyen, hanem konkrét figyelmeztetés mi történik.

**Comment by boborjan2** [comment]
Itt akkor eleg az, hogy nem indul automatikusan ujra, ha elmentik a jelszot/ssid-t?

**Comment by boborjan2** [comment]
0.1.15: done

**Comment by boborjan2** [comment]
itt mult el, hogy atirhato a sta konfig. Ugyanis a STA-ban valo elindulas mentette el belepesi infokat. Mivel megszunt az ujraindulas, megszunt a mentes is.

**Comment by dobrosi** [comment]
Logikus vhol. Szerintem allj vissza a korabbi megoldasr. A UI-on kell valami jobb workflow.

**Comment by boborjan2** [comment]
azt sajnos nem lehet megcsinalni, hogy APSTA uzemben a STA-t atkonfigoljuk: csak egy radio van a kutyuben, es igy az AP mindig azon a csatornan van, ahova a STA konfigolva van (hiszen annak alkalmazkodnia kell az AP-hez, akihez csatlakozik). Igy STA konfig utan mindenkepp ujra kell inditani az AP-t is. Az lehet esetleg egy megoldas, hogy ilyenkor nem STA modban indulunk ujra, hanem ugyanugy APSTA modban. De a telefonnal igy is ujra kell csatlakozni. Errol esetleg tajekoztatni kell a juzert az UIn. ?

**Comment by boborjan2** [comment]
Vagy azt lehet, h bementjuk a konfigot ujrainditas nelkul. Es akkor majd akkor derul ki, hogy mi van, amikor manualisan ujrainditja. Lehet, h ez a legjobb. Oda kell irni, hogy ujrainditas szukseges oszt csa. 
Mondjuk az ujrainditas nem APSTA modba teszi, hanem STA-ba, es ha vmi nem jo, akkor csak nez a juzer, mint ma mi.
AP modban ki kene jelezni, hogy a STA-val mi van.

**Comment by dobrosi** [comment]
Jo lenne minidig ugyanabba a modba visszacsatlakozni (ez ebben az esteben, meg az ujrainditas soran is igaz). Az mar sokat javitana a dolgon, ha APSTA-ba csatlakozik vissza.
Mivel a kutyu ujraindulasa es a csatalkozas elative gyors a kliens nem is vesz eszre semmit. Tajekoztatni a usert persze mindenkepp erdemes + esetleg elvenni a controlt es kiteve egy modal loading bitkolbaszt.

**Comment by boborjan2** [comment]
nem :) ezt mondom, hogy ha APSTA modba inditjuk ujra, az AP elmulik es jo esellyel masik csatornan indul el megint (a STA csatornajan). Tehat a juzernek a wifi menuben meg kell keresnie es ujra csatlakoznia kell sok esetben.

**Comment by dobrosi** [comment]
Ja ertem nincs ket wifi. OK, majd UI-t meg kell almodni picit. Az AP/STA mod akkor is kell ebben az esteben is, hogy visszatalaljon az admin oldalra, ha mar masik uton is (mar a sajat AP-t hasznalva).

Mas de fontos, hogyl AP modban a Probahivas gombot le kell venni.

Mit szolnal a UI-on egy ilyen ertelmezo abrara

[STA modban] Mobil -> Kaputelefon -> AP -> Internet -> SIP szerver

Amig elerhet zolddel jelezve, ami nincs meg piros. Ha minden zolt kint lehet a Probahivas gomb.

**Comment by boborjan2** [comment]
Legyen ez (?):

A gombot atirod, hogy "Mentes es ujrainditas". Amikor sikerul, feldobsz egy uzenetet, hogy  "csatlakozzon ujra" vagy vmi ertelmeset, amit ert a juzer.
En meg atirom, hogy induljon ujra APSTA modban. Illetve mindig abban, amiben eppen van.
Illetve csinalok egy /api/wstat statuszt, amibol kinyerheto, h van-e STA ill. AP.

**Comment by boborjan2** [comment]
Ja latom, hogy kb erre jutottal te is.
AP modban is lehet probahivas, ha a STA mukodik es okes.

**Comment by dobrosi** [comment]
OK

**Comment by boborjan2** [comment]
Es igen, probahivas button csak akkor legyen, ha jo a STA.
Elsokorben a wstat jelentese:
1 - AP ok
2 - STA ok
3 - mindketto OK.

**Comment by dobrosi** [comment]
4 - SIP connected?

**Comment by boborjan2** [comment]
hm az csak probahivaskor lesz initelve. Arra akkor lesz kulon statusz:
"api/sstat"
A tartalmat meg nem tudom. Majd ideirom

**Comment by boborjan2** [comment]
0.1.16
