### ISSUE TITLE
Szenzitív adataok ne utazzanak

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#39]
Jelenleg a /api/settings hívás visszaadja a jelszót. Meg kellene oldani, hogy vagy csak jelezve, hogy amúgy ki van töltve (****), vagy egyáltalán nem kellene visszaadni.
Meg kell oldani a kliens oldalon is a dolgot.

Ez vonatozhatna a "most advanced settings"-ekre is. Csak beállítani lehessen, kiolvasni nem.

**Comment by boborjan2** [comment]
OK. Amugy elvileg csak olyan netwrokon tudja olvasni, amelyik elvileg megbizhato (vagy AP modban, vagy a helyi halora csatlakozva. A helyi haloban elvileg bizik a user)

**Comment by dobrosi** [comment]
Jah csak open wifi van https nélkül! Így is erősen törhető a hálózat emiatt. Emiatt ha lehet csak legszükségesebb esetben utazzon a password.
https://www.androidauthority.com/capture-data-open-wi-fi-726356/

**Comment by dobrosi** [comment]
Ha HTTPS-t nem is, de esetleg RSA-t magában tud a kütyü?

**Comment by boborjan2** [comment]
1. Nem open a wifi, az AP-nak van passwordje mindene. Ha meg a user sajat halozata open, akkor meg ennyi
2. TUD https-t, csak kell certificate.

**Comment by dobrosi** [comment]
Ja jó téleg nem open, meg maga az AP jelszó majd egyedi lesz. OK.
Hát a saját hálózaton küldeni se célszerű. Akár egy trójai is kereshet jelszavakat, vagy a céges hálón bárki, plusz na szarul néz ki a plain jelszó kirakva.
De tulajdonképpen megszületett a döntés, hogy nem küldöd, vagy nem? Mondjuk ráér, de produktív módba kerül, akkor azért így szar magyarázni.
Hát akkor csináljuk a HTTPS-en
`
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365
`
