### ISSUE TITLE
Nem menthető a WIFI settings.

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#40]
1.) Nem menthető a WIFI settings.

**Comment by dobrosi** [comment]
Ha ez a wifi settings mentés után ne induljon újra az eszköz issue hozta elő és ez most plusz szívás, akkor állhatunk vissza is arra, max a ui-t alakítjuk intuitívabbra.

**Comment by boborjan2** [comment]
ja, itt van a kerdeses issue: https://github.com/dobrosi/jozsefutca/issues/36

erre vmilyen gombot kene varrni

**Comment by boborjan2** [comment]
0.1.16
