### ISSUE TITLE
Nem csatlakozik fel STA módban a WIFI-re.

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#41]
2.) Nem csatlakozik fel STA módban a WIFI-re.

**Comment by dobrosi** [comment]
Jó hír, hogy most csatlakozik. Vagy az 5g vagy a guest wifi okozhatta a gondot, vagy valami más. Átállítottan a default wifire és felcsatlakozott. Ami érdekes, hogy korábban guestre is felcsatlakozott. (az AP guest módját nem nagyon ismerem, használom) Most guestre költöztünk, a kapu meg a defaulton.

**Comment by boborjan2** [comment]
nalam termeszetesen nem reprodukalhato.
Javaslom, zarjuk es reopeneljuk, ha latod megint a porblemat.

**Comment by boborjan2** [comment]
ja, es amikor WPSsel jatszodtunk, akkor az nem lehetett 5GHz-es wifi? Mer a kutyumutyu nem tud 5GHzet, csak 2.4-et

**Comment by dobrosi** [comment]
Passz. Jo otlet, de akkor ez fontos. Csekkolom majd.
