### ISSUE TITLE
Nem nyit a kapunyitó (lakótelepi)

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#42]
3.) Nem nyit a kapunyitó (lakótelepi).

**Comment by boborjan2** [comment]
Ide kell majd egy advanced opcio, amivel az impulzus hosszat allitjuk.

"Kapunyito impulzus hossza", name="olen". Mertekegysege: ms

**Comment by dobrosi** [comment]
Amugy a kapunyitasnal a lakotelepinel nem is impulzus kell es a hossz sem fontos!
A lakotelepinel egy rovidzar a kapunyitas! Lsd csatolt image. Amikor nyitom a kaput en nyomom a gombot addig amig el nem engedem, szerintem azalatt rovidzarat kepzek, ami ugy 2-3 masodperc szokott lenni nalam es amit hallunk ilyenkor a lenti kozpont dallam hangjelzese, hogy nyit.
![IMG_20221007_084612](https://user-images.githubusercontent.com/1384173/194497693-2566461a-12e7-4f40-8a79-0dbc985bd67c.jpg)

**Comment by boborjan2** [comment]
ezt mind ertem, de nalunk nem kapcsolo van, hanem egy tranzisztor. azzal sorban van egy 50R ellenallas, ami korlatozza az aramot, ne menjen veletlenul tonkre a tranzisztor. Impulzushossz meg azer kell, mer ez egy szoftver, valamit irnom kell oda, meddig nyisson a tranzisztor (== meddig nyomod a kapcsolot)

**Comment by dobrosi** [comment]
A hossz annyi legyen, ameddig a user nyomja a beengedi kapcsolot (telin nehezebb gondolom, de a tone hossza ha lehet es van ilyen)

**Comment by boborjan2** [comment]
ja, ezt lehet. es ne legyen vmi max ertek? Ne menjen mar tonkre semmi.

ezt a mondatot nem ertem: "telin nehezebb gondolom, de a tone hossza ha lehet es van ilyen"

**Comment by dobrosi** [comment]
A telós beengedésnél is lehetne a nyomás hossza, de ott detektálni kell gondolom a tone jel hosszát.

**Comment by boborjan2** [comment]
nincs mar tone. Az a 60as evek. Egy flag megy at, hogy megnyomtak a #-t.
Sok codecen at se megy a sima tone.
A mineken atmenne mondjuk.

**Comment by dobrosi** [comment]
Ahogy latom ebben a Linphone kliens settingseben van ilyen:

Sávon belüli DTMF-ek küldése (RFC 2833) - alapból ez van becsekkolva

a másik

Sávon kívüli DTMF-ek küldése (SIP INFO) - alapból nincs becsekkolva

Nem ez az?

**Comment by boborjan2** [comment]
a tone rendszeru DTMF-hez kell a kliens oldalon dekoder. Akar szoftver akar hardver. Nalunk ilyen nincs.

**Comment by dobrosi** [comment]
Okay. Abban az esetben ha a telefonnal enged be (#), akkor kell egy adott hossz (1 sec tuti eleg amugy - de persze lehet conf is).
Ha fizikai gombot nyom magan a keszuleken, akkor meg szerencses lenne az a hossz, amit a user vegez.

**Comment by boborjan2** [comment]
0.1.16
