### ISSUE TITLE
Beépíteni a firmware buildbe, hogy a mindenkori aktuális (latest) frontend innen leszedhető

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#43]
Egyéb issue:
1.) Beépíteni a firmware buildbe, hogy a mindenkori aktuális (latest) frontend innen leszedhető:
curl -s https://api.github.com/repos/dobrosi/kaputelefon-frontend/releases/latest | grep browser_download_url | cut -d '"' -f 4

Amugy a firmware-t a frontend pedig innen updateli (automatikus frissítés gomb). Én jelenleg ide manuálisan releaselek a te repódból letöltve:
curl -s https://api.github.com/repos/dobrosi/jozsefutca/releases/latest | grep browser_download_url | cut -d '"' -f 4

**Comment by boborjan2** [comment]
0.1.16
