### ISSUE TITLE
Kaputelefon típus detekció

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#48]
Jelenleg az admin felületen megadható a kaputelefon típusa. Nem lenne jobb, ha ezt nem a user állítaná, hanem a hardwer detektálná valahogy?
Most pl külsőtáp van: Lakótelepi, nincs: Codefone.

**Comment by dobrosi** [comment]
Lehetne read only.

**Comment by boborjan2** [comment]
Laskomexnel is kulso tap van. Nem ezt szerintem nem bizzuk a hardverre, mer sose tudjuk meg mier nem megy valahol.
Ez egy alap parameter, mint a lakasszam.

**Comment by dobrosi** [comment]
En forditva latom. Pont nem biznam userre, mert o fogja elallitani es ezert nem fog mukodni. Spec most bennem is van egy bizonytalansag mit okoz ha atallitom mondjuk Codefonra. Egyaltalan az enyem milyen amugy? Es teszthivas miert mukodik Codefonnal is? Mi lesz az egyseg sugaru userrel? Ami neked alap az masnak nem. De amugy ez az info nem adott nalad? Mit okoz ha Codefonon hagyom?

**Comment by dobrosi** [comment]
Majd ha a lakomexhez erunk kigondoljuk higy kelunk at rajta. Meg akkor max laskomex: true/false ha sehogyse detektalhato.

**Comment by boborjan2** [comment]
az a baj, hogy a kulso tap nem jelent ilyen infot. A codefon is mukodhet kulso tappal.
