### ISSUE TITLE
A STA es AP/STA modba lepesnel halkabb legyen a beep

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#53]
Jelenleg a leghalkabb is nagyon hangos (fulet zavarhatja ha kozel a kagylo). Ennel inkabb lentebb kellene venni az ertekeket.
A jelenlegi minimum legyen a maximum. Ha nem lehet halkitani, akkor on/off es a most leghalkabb hangeron legyen.

**Comment by boborjan2** [comment]
0.1.16
