### ISSUE TITLE
Parameter feluldefinialas nem standard alapjan tortenik

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#55]
Aprosag, de most pont nem ugy mukodik, mint a standard.
Ha duplan szerepel ugyanaz a parameter a request URL-ben, akkor nem string eseten az utolso parancs, aminek a veglegesnek kellene lennie.
Pl:
https://www.arukereso.hu/memoria-modul-c3577/?orderby=1&orderby=2
Ugyanaz, mint
https://www.arukereso.hu/memoria-modul-c3577/?orderby=2

A kapuban ez pont forditva mukodik (nem feltetelen gond, mert tudok tekerni a kliensen, de esetleg ha meglehetne forditani szebb lenne)
Ha:
```
curl -X PUT http://kaputelefon.local/api/icom?hdpx=0&hdpx=1
```
Jelenleg:
```
curl -X GET http://kaputelefon.local/api/icom
{"type": "mkt","testmode": "1","ssid": "dewifi123","password": "19pottom79.","code":"1","rvol":"1","ivol":"50","cvol":"1","hvol":"70","vvol":"70","lvol":"70","ctim":"0","sta":"1","voip":"1","hdpx":"0","flog":"0","dnsc":"1","rfc7710":"1"}
```
Elvart:
```
curl -X GET http://kaputelefon.local/api/icom
{"type": "mkt","testmode": "1","ssid": "dewifi123","password": "19pottom79.","code":"1","rvol":"1","ivol":"50","cvol":"1","hvol":"70","vvol":"70","lvol":"70","ctim":"0","sta":"1","voip":"1","hdpx":"1","flog":"0","dnsc":"1","rfc7710":"1"}
```

**Comment by boborjan2** [comment]
1.20

**Comment by dobrosi** [comment]
Ha jol ertem ebben a verzioban meg fogod cserelni?

**Comment by boborjan2** [comment]
igen, mar megvan, csak nincs meg publikalva

**Comment by dobrosi** [comment]
Ok, akkor majd a klienst utana igazitom. Azt forgasd majd bele.

**Comment by dobrosi** [comment]
Hozzaigazitva a kliens. Ezzel most kellene egy uj firmware release (0.1.21)!

**Comment by boborjan2** [comment]
fenn van
