### ISSUE TITLE
A log lekeres elmult

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#59]
Erre: http://kaputelefon.local/api/logfile
200 http code-ot, de ures oldalt kapok.

**Comment by boborjan2** [comment]
akkor ez megis megy (?)

**Comment by dobrosi** [comment]
Jelenleg megy. Zard le, max ujranyitom es megprobalom reprodukalni.

boborjan2 ***@***.***> ezt írta (időpont: 2022. dec. 9., P,
16:10):
