### ISSUE TITLE
Online logogolas megvalositasa

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#60]
Igy lehet logot kuldeni (warn/info/error):
/log/warn/{deviceId}/{message}
```
curl -X 'GET' \
  'https://kapulog.herokuapp.com/log/warn/123/Hello' \
  -H 'accept: */*'
```
vagy
```
curl -X 'POST' \
  'https://kapulog.herokuapp.com/log/warn/123' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d 'Hello Teszt Elek!'
```
Reszletes doksi es proba lehetoseg:
https://kapulog.herokuapp.com/swagger-ui.html

Majd megmutatom, hogyan lehet nezegetni.
https://console.cloud.google.com/logs

**Comment by boborjan2** [comment]
Errorhibat dob a post-ra. es nem megy a doksi link.

**Comment by boborjan2** [comment]
illetve a content type az json? nem text/plain?

**Comment by boborjan2** [comment]
ja es. https lehet csak?

**Comment by dobrosi** [comment]
1., 2, HTTP-n megy
Link csere kell.
Ez az uj.
http://kapulog.dyndns.hu/

3. content type az json - igen

Andris


Andris

boborjan2 ***@***.***> ezt írta (időpont: 2022. dec. 8., Cs,
14:13):

**Comment by dobrosi** [comment]
Itt vannak az endpointok:
http://kapulog.dyndns.hu/swagger-ui/

Itt egy pelda:

curl -X 'POST' \  'http://kapulog.dyndns.hu/log/warn/123' \  -H
'accept: */*' \  -H 'Content-Type: application/json' \  -d 'Hello
world!'


András DOBROSI ***@***.***> ezt írta (időpont: 2022. dec. 8., Cs,
19:39):

**Comment by boborjan2** [comment]
http://kapulog.dyndns.hu/swagger-ui/:
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Sat Dec 10 22:55:21 CET 2022
There was an unexpected error (type=Not Found, status=404).

**Comment by boborjan2** [comment]
http://kapulog.dyndns.hu/log/warn/123

detto

**Comment by dobrosi** [comment]
A doksi jo url ez:

http://kapulog.dyndns.hu/swagger-ui/index.html

Van GET-es es POST-os endpoint, de kulonbozik az URL olyankor, mert
utobbinal nincs benne a message (lasd doksi)

A GET-es igy jo:
http://kapulog.dyndns.hu/log/warn/deviceId/Hello%20world%21

De inkabb a POST-ot hasznald ( akkor nem kell Url encoding)!

Csekkold a swaggert, az nem hazudik!


boborjan2 ***@***.***> ezt írta (időpont: 2022. dec. 10., Szo
22:56):

**Comment by boborjan2** [comment]
1.20

settings?hlog=1 kell hozza

64kbyte-os buffer van jelenleg.

es http, nem https.
