### ISSUE TITLE
VOIP beallitasok modositas csak ujrainditas utan lepnek ervenybe

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#61]
Ha hivast kezdemenyezo, vagy hivast fogado VOIP beallitast modositok, akkor probahivasra meg az elozo beallitassal tortenik a hivas. Csak ujrainditas utan lep ervenybe az utolso modositas.
Ez zavaro igy: jo lenne ha a probahivas a legutolso beallitassal mukodne.

**Comment by boborjan2** [comment]
1.19
