### ISSUE TITLE
Nem ismert allapotba lep szerviz modbol

### ISSUE THREAD

**Issue by dobrosi** [dobrosi/jozsefutca#62]
Ha szervizmodban vagyok (STA , vagy STAAP), majd itt tobb masodpercig (~5 sec) nzomom a kapubeengedo gombot, akkor nagy frekvenciaval villog a zold led es nem elerheto se STA admin, es nem lathato tovabb, mint AP (ha abban voltam).
Tudatos, vagy bug?

**Comment by boborjan2** [comment]
Ez a WPS. Ilyenkor tudnad automatan hozzaloni a ruteredhez.
